### 책 전체 조회 API
GET http://localhost:8080/books?title=투자3
Content-Type: application/json

### 책 등록
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "첵 제목 테스트2",
  "author": "신선호",
  "categoryList": [
    1
  ]
}


### 책 수정
PATCH http://localhost:8080/books/15
Content-Type: application/json

{
  "title": "첵 제목 테스트",
  "author": "신선호",
  "categoryList": [
    4,
    5
  ],
  "isRentable": false
}


### 카테고리 등록
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "소설"
}


### 책 카테로리로 조회
GET http://localhost:8080/books/categories/1
Content-Type: application/json